contentColumnType: string(1200)
fieldGroup: 1ebe758b-faa7-4e26-8867-fc4c02b80dfb
handle: alert
instructions: ''
name: 'Alert Text'
searchable: true
settings:
  byteLimit: null
  charLimit: 300
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'PREVIEW — Full portfolio coming soon. Thanks for visiting, check back again!'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
