contentColumnType: string(576)
fieldGroup: 1ebe758b-faa7-4e26-8867-fc4c02b80dfb
handle: author
instructions: ''
name: Author
searchable: true
settings:
  byteLimit: null
  charLimit: 144
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Evander Batson'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
