contentColumnType: text
fieldGroup: 859871ca-1e6f-44a0-97d5-ab664a5cf156
handle: bodyCopy
instructions: ''
name: 'Body Copy'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
