contentColumnType: text
fieldGroup: 3773e46a-6884-4fb0-a638-76db810008f4
handle: linkTable
instructions: ''
name: 'Link Table'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'First Column'
            -
              - handle
              - firstCol
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Second Column'
            -
              - handle
              - secondCol
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'Third Column'
            -
              - handle
              - thirdCol
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - 'Fourth Column'
            -
              - handle
              - fourthCol
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - 'Link label'
        -
          - col2
          - ''
        -
          - col3
          - ''
        -
          - col4
          - ''
    -
      __assoc__:
        -
          - col1
          - URL
        -
          - col2
          - ''
        -
          - col3
          - ''
        -
          - col4
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
