contentColumnType: text
fieldGroup: 859871ca-1e6f-44a0-97d5-ab664a5cf156 # Copy
handle: loglinePosition
instructions: ''
name: 'Logline Position'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Product Designer'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
