contentColumnType: text
fieldGroup: 859871ca-1e6f-44a0-97d5-ab664a5cf156
handle: loglineUrlTitle
instructions: ''
name: 'Logline URL Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
