contentColumnType: string(400)
fieldGroup: 859871ca-1e6f-44a0-97d5-ab664a5cf156
handle: masthead
instructions: ''
name: Masthead
searchable: true
settings:
  byteLimit: null
  charLimit: 100
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
