contentColumnType: text
fieldGroup: 3b9ebc55-aaf6-419e-9966-cc3150c0241b # Projects
handle: projectAwards
instructions: ''
name: 'Project Awards'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes:
    - 9cc06734-586d-496c-8b86-0e2a97ed9626 # Images
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
