contentColumnType: string(352)
fieldGroup: 3b9ebc55-aaf6-419e-9966-cc3150c0241b # Projects
handle: projectTitle
instructions: ''
name: 'Project Title'
searchable: false
settings:
  byteLimit: null
  charLimit: 88
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'The Met'
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
