fieldLayouts:
  d0f5ce82-4300-4412-b8d9-0b059d405d5c:
    tabs:
      -
        elements:
          -
            fieldUid: 9bebd901-90cb-4ddc-a068-c71343bc5a9e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f2b32a82-6f59-48eb-90c4-be1544a03c7c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ff77cfee-d36c-421e-9cfa-4b9c9728b217
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 27bff9a5-e035-4d96-833b-c2ae3c31a0da
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6f3bbbb7-a66f-4b60-9f00-2f34d6a10944
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1bed5876-1717-4b3e-bf90-056ea5a70c27
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Global Settings'
        sortOrder: 1
handle: global
name: Global
