enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  8fe75711-323f-403c-816d-5747b34337b7: # Portfolio
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
