enableVersioning: true
handle: project
name: Project
propagationMethod: all
siteSettings:
  8fe75711-323f-403c-816d-5747b34337b7:
    enabledByDefault: true
    hasUrls: true
    template: project/_entry
    uriFormat: 'project/{slug}'
type: channel
