enableVersioning: true
handle: services
name: Services
propagationMethod: all
siteSettings:
  8fe75711-323f-403c-816d-5747b34337b7: # Portfolio
    enabledByDefault: true
    hasUrls: true
    template: services/_entry
    uriFormat: services
type: single
